- hosts: all
  gather_facts: no
  vars:
    ansible_user: root
    ansible_host_key_checking: false
  tasks:
    - name: Wait for target connection to become reachable/usable
      wait_for_connection:
    - name: Add node apt sources
      shell: curl -sL https://deb.nodesource.com/setup_15.x | bash -

    - name: Install nodejs
      apt:
        name: nodejs

    - name: Install global npm packages
      shell: npm i -g nodemon ts-node typescript

    - name: Git checkout to /app directory
      git:
        repo: "https://github.com/EcoFootprintHackYeah/eco-footprint-backend.git"
        dest: /app

    - name: Get all dependencies
      shell: npm i
      args:
        chdir: /app


    - name: Install the app
      shell: npm run build
      args:
        chdir: /app

    - name: Copy service file
      copy:
        src: api.service
        dest: /etc/systemd/system/

    - name: Force systemd to reread configs
      systemd:
        daemon_reload: yes

    - name: Start api service
      systemd:
        state: started
        name: api
